Repository GymManna/FrontEnd, pull requests merged in 2023-03, with the labels that each got.

#24 [#23]로그인, 회원가입 페이지 BackEnd와 연동
  src/views/auth/SignInEmail.vue
  src/views/auth/SignUp.vue
Labels: feat

#26 [#25]마이페이지 컴포넌트 출력 방식 변경,
  src/components/layout/VHeader.vue
  src/components/user/EditMyInfo.vue
  src/components/user/JoinedGathering.vue
  src/components/user/MyCommGathering.vue
  src/components/user/MyCommPhoto.vue
  src/components/user/MyPageMenu.vue
  src/main.js
  src/plugins/GlobalMethod.js
  src/router/index.js
  src/views/auth/SignInEmail.vue
  src/views/user/EditMyInfo.vue
  src/views/user/JoinedGathering.vue
  src/views/user/MyCommGathering.vue
  src/views/user/MyCommPhoto.vue
  src/views/user/MyPageMenu.vue
  src/views/user/MyPageView.vue
Labels: feat, refactoring

#28 [#27]feat: 만나 게시판 관련 페이지 초안 작성
  src/components/gathering/GatheringMainMap.vue
  src/components/gathering/js/GatheringMainMap.js
  src/components/gathering/scss/GatheringMainMap.scss
  src/router/index.js
  src/views/article/gathering/ArticleGathering.vue
  src/views/article/gathering/ArticleGatheringView.vue
  src/views/article/gathering/CreateArticleGatheringView.vue
  src/views/article/gathering/DetailArticleGatheringView.vue
  src/views/article/gathering/EditArticleGatheringView.vue
Labels: feat

#31 [#29]feat: 만나 게시판 버튼 axios 기본 기능 구현
  src/components/user/EditMyInfo.vue
  src/views/article/gathering/CreateArticleGatheringView.vue
  src/views/article/gathering/DetailArticleGatheringView.vue
  src/views/article/gathering/EditArticleGatheringView.vue
  src/views/auth/SignUp.vue
  src/views/auth/SignUpKakao.vue
Labels: feat, refactoring

#34 [#32]feat: 페이지마다 로그인정보 적용 중
  package-lock.json
  package.json
  src/components/layout/VHeader.vue
  src/main.js
  src/store/index.js
  src/views/article/gathering/ArticleGatheringView.vue
  src/views/article/gathering/CreateArticleGatheringView.vue
  src/views/article/gathering/DetailArticleGatheringView.vue
  src/views/article/gathering/EditArticleGatheringView.vue
  src/views/auth/SignInEmail.vue
  src/views/auth/SignUp.vue
  src/views/auth/SignUpKakao.vue
Labels: feat

#37 [#35]feat: 사진 인증 게시판 개발
  src/views/article/photo/ArticlePhoto.vue
  src/views/article/photo/CreateArticlePhoto.vue
  src/views/article/photo/DetailPhoto.vue
Labels: feat

#38 [#32]feat: 회원가입 시 로그인 정보 출력으로 변경
  src/components/layout/VHeader.vue
  src/store/index.js
  src/views/article/gathering/ArticleGatheringView.vue
  src/views/auth/SignInEmail.vue
  src/views/auth/SignUp.vue
  src/views/auth/SignUpKakao.vue
Labels: feat

#41 [#32]카카오 로그인, 카카오 회원가입 구현
  src/views/auth/SignIn.vue
  src/views/auth/SignUpKakao.vue
Labels: feat

#42 [#32]feat: 만나 게시판 리스트 가져오기,
  src/components/layout/VHeader.vue
  src/components/user/EditMyInfo.vue
  src/views/article/gathering/ArticleGatheringView.vue
  src/views/article/gathering/CreateArticleGatheringView.vue
  src/views/auth/SignIn.vue
Labels: feat

#43 [#32]마이페이지 오류 수정,
  src/components/user/EditMyInfo.vue
  src/views/article/gathering/ArticleGatheringView.vue
  src/views/article/gathering/DetailArticleGatheringView.vue
Labels: bug, feat

#44 [#32]병합
  src/components/user/EditMyInfo.vue
Labels: bug

#45 회원정보 수정 버그잡기
  src/components/gathering/GatheringMainMap.vue
  src/components/user/EditMyInfo.vue
  src/views/article/gathering/ArticleGatheringView.vue
Labels: bug
